### ISSUE TITLE
File uploading not working properly

### ISSUE THREAD

**Issue by geogeorgejoseph** [getgrav/grav-plugin-form#550]
**Tring to upload file, but getting below errors**

form.vendor.js:5 Uncaught TypeError: Cannot read properties of undefined (reading 'trim')
    at D.addedfile (form.vendor.js:5:11362)
    at D.value (form.vendor.js:5:1513)
    at D.value (form.vendor.js:5:25886)
    at HTMLInputElement.<anonymous> (form.vendor.js:5:17561)

Please give me a solution

**Comment by michaelschoenbaechler** [comment]
Also had the same issue, was trying for hours. Try to remove "reset: true". 
Worked for me.
